[theme]
base = "light"
primaryColor = "#c4452f"
backgroundColor = "#f5f0e8"
secondaryBackgroundColor = "#ffffff"
textColor = "#2b2b2b"
font = "Georgia"

[server]
headless = true                         # ✅ Required for Streamlit Cloud
enableCORS = false
enableXsrfProtection = false
port = 8501

[client]
showSidebarNavigation = true
toolbarMode = "minimal"

[ui]
hideTopBar = false

[runner]
fastReruns = true
magicEnabled = true

[browser]
gatherUsageStats = false