[theme]
base = "light"
primaryColor = "#c4452f"              # Muted warm red (similar to Anies–Muhaimin red)
backgroundColor = "#f5f0e8"           # Warm cream background — easy on the eyes, excellent for print
secondaryBackgroundColor = "#ffffff"  # White for cards and secondary sections
textColor = "#2b2b2b"                 # Neutral dark gray for excellent readability
font = "Georgia"                        # Classic serif font for an editorial / map-report feel

[server]
headless = false
enableCORS = false
enableXsrfProtection = false
port = 8501

[client]
showSidebarNavigation = true
toolbarMode = "minimal"

[ui]
hideTopBar = false

[runner]
fastReruns = true
magicEnabled = true

[browser]
gatherUsageStats = false