[theme]
base = "light"
primaryColor = "#c4452f"              # Muted warm red (editorial tone)
backgroundColor = "#f5f0e8"           # Warm cream background
secondaryBackgroundColor = "#ffffff"  # White cards
textColor = "#2b2b2b"                 # Neutral dark gray for readability
font = "Georgia"                        # Serif for print-style layout

[server]
headless = true                         # ✅ Required for Streamlit Cloud
enableCORS = false
enableXsrfProtection = false
port = 8501                             # Default port Streamlit listens to

[client]
showSidebarNavigation = true
toolbarMode = "minimal"

[ui]
hideTopBar = false

[runner]
fastReruns = true
magicEnabled = true

[browser]
gatherUsageStats = false