[theme]
base = "dark"
primaryColor = "#4DB6AC"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E252F"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = false
enableCORS = false
enableXsrfProtection = false
port = 8501

[client]
showSidebarNavigation = true
toolbarMode = "minimal"

[ui]
hideTopBar = false

[runner]
fastReruns = true
magicEnabled = true

[browser]
gatherUsageStats = false