[theme]
base = "dark"
primaryColor = "#4DB6AC"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E252F"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[ui]
hideTopBar = false
hideSidebarNav = false

[client]
toolbarMode = "minimal"

[runner]
fastReruns = true
magicEnabled = true

[browser]
gatherUsageStats = false